# Generated by Django 3.1.7 on 2021-02-25 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kathakar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=255)),
                ('prasidha_nam', models.CharField(max_length=255)),
                ('gaon', models.CharField(max_length=255)),
                ('janam_tithi', models.DateTimeField()),
                ('vriti', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Katha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=255)),
                ('kathakar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katha.kathakar')),
            ],
        ),
    ]
