# Generated by Django 3.2 on 2022-04-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='manushya',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='manushya',
            name='gaon',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Gaon',
        ),
    ]
