# Generated by Django 3.2 on 2022-05-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramjee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harkare',
            name='vibhakti',
            field=models.CharField(choices=[('KH', 'Kahani'), ('SH', 'Shashtra'), ('VD', 'Ved'), ('PN', 'Puran'), ('LK', 'Lokmanya'), ('KY', 'Kavya'), ('PY', 'Padya'), ('PM', 'Prem'), ('BR', 'Gyan'), ('SR', 'Siyaram')], default='SR', max_length=2),
        ),
    ]
